'use strict';
(()=>{
const D=window.STRATA_DATA, charts={}, M=D.models, F='IBM Plex Mono';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ids=D.rows.map(r=>r.key), label=k=>M[k]?.short||k, color=k=>M[k]?.color||'#737a82';
const root={backgroundColor:'transparent',animation:!matchMedia('(prefers-reduced-motion: reduce)').matches,textStyle:{fontFamily:F,color:'#a3a8ad',fontSize:10},aria:{enabled:true},tooltip:{trigger:'axis',confine:true,backgroundColor:'#17191f',borderColor:'#ffffff30',textStyle:{color:'#f2f2ed',fontFamily:F,fontSize:11},axisPointer:{type:'shadow'}},toolbox:{right:0,top:0,feature:{saveAsImage:{title:'Save chart',backgroundColor:'#080808',pixelRatio:2}},iconStyle:{borderColor:'#737a82'}}};
function paint(id,opt){let c=charts[id]||(charts[id]=echarts.init(document.getElementById(id),null,{renderer:'canvas'}));c.setOption({...root,...opt},true);}
function bars(id,rows,value,unit,dec=1,extra){rows=rows.filter(r=>value(r)!=null);paint(id,{grid:{left:116,right:54,top:25,bottom:28},tooltip:{...root.tooltip,formatter:ps=>{const r=rows[ps[0].dataIndex];return `<b>${esc(label(r.key))}</b><br>${Number(value(r)).toFixed(dec)} ${unit}${extra?'<br>'+esc(extra(r)):''}`;}},xAxis:{type:'value',name:unit,nameLocation:'middle',nameGap:22,nameTextStyle:{fontSize:9,color:'#737a82'},splitLine:{lineStyle:{color:'#ffffff09'}},axisLabel:{fontSize:9,color:'#737a82'}},yAxis:{type:'category',inverse:true,data:rows.map(r=>label(r.key)),axisLabel:{color:'#a3a8ad',fontSize:10},axisTick:{show:false},axisLine:{show:false}},series:[{type:'bar',barWidth:15,data:rows.map(r=>({value:value(r),itemStyle:{color:color(r.key),opacity:r.key==='strata'?1:.78,borderRadius:[0,3,3,0]}})),label:{show:true,position:'right',color:'#d9d9d5',fontFamily:F,fontSize:10,formatter:p=>Number(p.value).toFixed(dec)}}]});}
let qmode='hermes',wmode='hermes';
function quality(){bars('chart-quality',D.rows,r=>r[qmode==='hermes'?'hermes_score':'tools_score'],'/100',1);}
function wall(){bars('chart-agent-wall',D.rows,r=>r[wmode==='hermes'?'hermes_mean_case_wall':'tools_wall'],'seconds',1);}
document.querySelectorAll('[data-quality]').forEach(b=>b.addEventListener('click',()=>{qmode=b.dataset.quality;document.querySelectorAll('[data-quality]').forEach(x=>x.setAttribute('aria-pressed',x===b));quality();}));
document.querySelectorAll('[data-wall]').forEach(b=>b.addEventListener('click',()=>{wmode=b.dataset.wall;document.querySelectorAll('[data-wall]').forEach(x=>x.setAttribute('aria-pressed',x===b));wall();}));
quality();wall();bars('chart-decode',D.rows,r=>r.he09_native_tg,'tok/s',1,r=>r.he09_timing);bars('chart-he-wall',D.rows,r=>r.he09_wall,'seconds',2);
function lines(id,rows,xkey,vkey,unit,dec=1){
 const keys=[...new Set(rows.map(r=>r.modelId))],xs=[...new Set(rows.map(r=>r[xkey]))].sort((a,b)=>a-b);
 paint(id,{grid:{left:49,right:23,top:74,bottom:39},legend:{top:0,type:'scroll',data:keys.map(label),textStyle:{fontFamily:F,fontSize:9,color:'#a3a8ad'},pageTextStyle:{color:'#737a82'},pageIconColor:'#39d0ff',pageIconInactiveColor:'#373b43',itemWidth:13,itemHeight:7},tooltip:{...root.tooltip,axisPointer:{type:'line'},formatter:ps=>`<b>${esc(ps[0].axisValue)} ${xkey==='inputTokens'?'input':'cached depth'} tokens</b><br>`+ps.map(p=>{const r=p.data.record;return `${p.marker} ${esc(p.seriesName)}: ${Number(p.value).toFixed(dec)} ${unit}${r.modelId==='strata'&&vkey==='tg'&&!r.equal512Output?' · output diagnostic':''}${vkey==='pp'&&r.replayTokens!=null?' · replay '+r.replayTokens:''}`;}).join('<br>')},xAxis:{type:'category',data:xs,axisLabel:{fontSize:9,color:'#737a82',formatter:v=>Number(v)===0?'0':Number(v)/1000+'K'},axisLine:{lineStyle:{color:'#ffffff25'}},axisTick:{show:false}},yAxis:{type:'value',name:unit,nameTextStyle:{fontFamily:F,fontSize:9,color:'#737a82'},axisLabel:{fontSize:9,color:'#737a82'},splitLine:{lineStyle:{color:'#ffffff0b'}}},series:keys.map(k=>({type:'line',name:label(k),showSymbol:true,symbolSize:k==='strata'?7:4,symbol:'circle',lineStyle:{width:k==='strata'?3:1.7,color:color(k),opacity:k==='strata'?1:.7},itemStyle:{color:color(k)},connectNulls:false,data:xs.map(x=>{const r=rows.find(r=>r.modelId===k&&r[xkey]===x);return r?{value:r[vkey],record:r,symbol:k==='strata'&&vkey==='tg'&&!r.equal512Output?'emptyCircle':'circle'}:null;})}))});
}
lines('chart-cold',D.cold,'inputTokens','tps','tok/s');
function append(){const size=Number(document.getElementById('append-size').value),rs=D.append.filter(r=>r.promptTokens===size);lines('chart-append',rs,'depthTokens','pp','tok/s');lines('chart-append-tg',rs,'depthTokens','tg','tok/s');lines('chart-ttfp',rs.map(r=>({...r,ttfp:r.ttfpMs/1000})),'depthTokens','ttfp','seconds',2);}
append();document.getElementById('append-size').addEventListener('change',append);
bars('chart-kl',D.rows,r=>r.fidelity_kl,'KL',4);bars('chart-top1',D.rows,r=>r.fidelity_top1,'%',2);bars('chart-ppl',D.rows,r=>r.fidelity_ppl,'PPL',4);
const resources=D.resources.map(r=>({...r,key:r.modelId}));bars('chart-assets',resources,r=>r.packageGiB,'GiB',1);bars('chart-memory',resources,r=>r.servingGiB,'GiB',1,r=>r.method);
const names={he09:'HE0–9','counting-zero-replay':'Append / cold prefill',fidelity:'Fidelity',tools:'Tools',hermes:'Hermes'};
document.getElementById('memory-rows').innerHTML=D.memory.map(r=>`<tr><td>${esc(names[r.panel]||r.panel)}</td><td>${(r.ready_ram_used_bytes/2**30).toFixed(2)} GiB</td><td>${(r.peak_ram_used_bytes/2**30).toFixed(2)} GiB</td><td>${(r.minimum_available_bytes/2**30).toFixed(2)} GiB</td></tr>`).join('');
new ResizeObserver(()=>Object.values(charts).forEach(c=>c.resize())).observe(document.querySelector('main'));
window.strataCharts=()=>({charts:Object.keys(charts),quality:qmode,wall:wmode,appendSize:Number(document.getElementById('append-size').value),modelCount:D.rows.length});
})();
